name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [17]
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew generateCode build --stacktrace --warning-mode fail
